version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
updates:
  - package-ecosystem: npm
    directory: '/'
    registries:
      - npm-github
    schedule:
      interval: 'monthly'
      time: '09:00'
    open-pull-requests-limit: 10
    rebase-strategy: 'disabled'
    versioning-strategy: increase
    pull-request-branch-name:
      separator: '-'
