version: '3'

services:
  # Serviço para o aplicativo Phoenix
  web:
    build:
      context: .
    command: /bin/sh entrypoint.sh
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db  
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/phil_collins_db_dev"
      MIX_ENV: "prod"
      SECRET_KEY_BASE: "+C6rOXXAZYE5uUMIsJ75HsXD8rtVrihxJpNoq22E7J4ueqFlvO/5Yzuz81AE60nx"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phil_collins_db_dev
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_HOST: "host.docker.internal"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
