version: '3'

services:
  # Serviço para o aplicativo Phoenix
  web:
    build:
      context: .
    command: /bin/sh entrypoint.sh
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db  
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MIX_ENV: "prod"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
